spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/salons
spring.datasource.username=postgres
spring.datasource.password=Fihgter003
spring.jpa.hibernate.ddl-auto=validate
spirng.jpa.open-in-view=enabled
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

